# Site settings
title: David Aramant's Blog
email: davidaramant@gmail.com
description: >
  yet another blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: davidaramant
github_username:  davidaramant

# Build settings
markdown: kramdown
